Add CYGNSS_L2_SURFACE_FLUX_V3.2.cfg
podaac/forge-tig-configuration pull request #87
Opened 2024-08-28 14:18 UTC by yiboj

2024-09-06 01:09 UTC, jamesfwood requested changes

2024-09-06 01:09 UTC, jamesfwood commented on config-files/CYGNSS_L2_SURFACE_FLUX_V3.2.cfg
> +    "footprint": {
@yiboj This shouldn't have footprint since it's a global bbox.  Can you update this?

2024-09-09 02:55 UTC, yiboj commented
sure, sorry for the late reply, this email goes to spam
________________________________
From: James Wood ***@***.***>
Sent: Thursday, September 5, 2024 6:09 PM
To: podaac/forge-tig-configuration ***@***.***>
Cc: Jiang, Yibo (US 398I) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [podaac/forge-tig-configuration] Add CYGNSS_L2_SURFACE_FLUX_V3.2.cfg (PR #87)


@jamesfwood requested changes on this pull request.

________________________________

In config-files/CYGNSS_L2_SURFACE_FLUX_V3.2.cfg<https://urldefense.us/v3/__https://github.com/podaac/forge-tig-configuration/pull/87*discussion_r1746360410__;Iw!!PvBDto6Hs4WbVuu7!LMJZdQKTBtZv5-E9-hN_QfGyL-bGt8cfGzVtcVTaNifwWe4xFKUiFcvH1lZQFXjo7WmusVl--JOnxCYdJcshnWsb1psh2N4$>:

> @@ -0,0 +1,85 @@
+{
+    "shortName": "CYGNSS_L2_SURFACE_FLUX_V3.2",
+    "latVar": "lat",
+    "lonVar": "lon",
+    "timeVar": "time",
+    "is360": true,
+    "tiles": {
+        "steps": [
+            30,
+            14
+        ]
+    },
+    "footprint": {


@yiboj<https://urldefense.us/v3/__https://github.com/yiboj__;!!PvBDto6Hs4WbVuu7!LMJZdQKTBtZv5-E9-hN_QfGyL-bGt8cfGzVtcVTaNifwWe4xFKUiFcvH1lZQFXjo7WmusVl--JOnxCYdJcshnWsbo6i5Gko$> This shouldn't have footprint since it's a global bbox. Can you update this?

—
Reply to this email directly, view it on GitHub<https://urldefense.us/v3/__https://github.com/podaac/forge-tig-configuration/pull/87*pullrequestreview-2284391864__;Iw!!PvBDto6Hs4WbVuu7!LMJZdQKTBtZv5-E9-hN_QfGyL-bGt8cfGzVtcVTaNifwWe4xFKUiFcvH1lZQFXjo7WmusVl--JOnxCYdJcshnWsb3xcGias$>, or unsubscribe<https://urldefense.us/v3/__https://github.com/notifications/unsubscribe-auth/AFKQ4E6B7GNFFWLRJW23XGLZVD6GHAVCNFSM6AAAAABNIM5KLGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOBUGM4TCOBWGQ__;!!PvBDto6Hs4WbVuu7!LMJZdQKTBtZv5-E9-hN_QfGyL-bGt8cfGzVtcVTaNifwWe4xFKUiFcvH1lZQFXjo7WmusVl--JOnxCYdJcshnWsb8J7L6sM$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-11-26 22:26 UTC, jamesfwood approved these changes

2024-11-26 22:26 UTC, merged